--- #
management:
  endpoint:

    # shutdown 설정 노출 여부
    shutdown:
      enabled: true
  endpoints:

    # jmx 관련 설정(e.g. health, info 옵션 포함)
    jmx:
      exposure:
        include: "health,info"

    # web 에 노출할 요소들 설정 및 env, beans 노출 제외
    web:
      exposure:
        include: "*"
        exclude: "env,beans"

---
management:
  endpoint:
    health:
      show-details: always # 헬스 정보를 더 자세히 보기 위한 옵션
      show-components: always # 각 헬스 컴포넌트의 상태 정보만 간략하게 노출

---
# java, os ?? ??

management:
  info:
    java:
      enabled: true
    os:
      enabled: true

---
# env ?? ??

management:
  info:
    env:
      enabled: true

info:
  app:
    name: hello-actuator
    company: cooper


---
# log level 설정

logging:
  level:
    com.cooper.springactuator.controller: debug

---
# endpoint 변경
## /actuator/{endpoint} -> /manage/{endpoint}

management:
  endpoints:
    web:
#      base-path: "/manage"

server:
  tomcat:
    mbeanregistry:
      enabled: true
