--- #
management:
  endpoint:

    # shutdown ????? ???
    shutdown:
      enabled: true
  endpoints:

    # jmx ? health, info ??
    jmx:
      exposure:
        include: "health,info"

    # web ? ?? ????? ????? env, beans ??
    web:
      exposure:
        include: "*"
        exclude: "env,beans"

---
management:
  endpoint:
    health:
      show-details: always # ?? ??? ???? ?? ?? ?? ??
      show-components: always # ? ?? ????? ?? ??? ???? ??

---
# java, os ?? ??

management:
  info:
    java:
      enabled: true
    os:
      enabled: true

---
# env ?? ??

management:
  info:
    env:
      enabled: true

info:
  app:
    name: hello-actuator
    company: cooper


---
# log level ??

logging:
  level:
    com.cooper.springactuator.controller: debug

---
# endpoint ?? ??
## /actuator/{endpoint} -> /manage/{endpoint}

management:
  endpoints:
    web:
#      base-path: "/manage"
