spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        query:
          in_clause_parameter_padding: true # 2^n padding option
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://localhost:3306/cooper_db
    username: root
    password: cooper2021
    driver-class-name: com.mysql.cj.jdbc.Driver

---

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3
          multiplier: 2
    template:
      mandatory: true
      receive-timeout: 5000
      reply-timeout: 5000
      retry:
        enabled: true
        initial-interval: 1000
        max-attempts: 3
        multiplier: 2
