# default
spring:
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: local
  batch:
    job:
      names: ${job.name:NONE}
      enabled: false # ????? ??? ???? ???.
    jdbc:
      initialize-schema: always
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cooper_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: cooper2021
  jpa:
    show-sql: true

---

spring:
  config:
    activate:
      on-profile: test
  jpa:
    database: h2
