spring:
  application:
    name: presigned_url
  cloud:
    aws:
      s3:
        region: # TODO region
      credentials:
        access-key: # TODO access-key
        secret-key: # TODO secret-key
  servlet:
    multipart:
      max-file-size: 10MB # multipart 데이터 용량 제한을 위한 프로퍼티
      max-request-size: 10MB # multipart 데이터 용량 제한을 위한 프로퍼티
logging:
  level:
    io:
      awspring:
        cloud: debug

aws:
  bucket:
    name: # TODO bucket-name
