spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 6c39525c457e9ec6226c4dcef6130eaf
            client-secret: [add secret-key]
            client-authentication-method: POST
            scope:
              - profile_nickname
              - profile_image
            client-name: practice
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/oauth/kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
logging:
  level:
    com.cooper.com.cooper.springsecurityoauth: debug
