spring:
  profiles:
    active: local
---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver

---

spring:
  config:
    activate:
      on-profile: mysql-local
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    properties:
      hibernate.format_sql: true
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/spring_batch?useUnicode=true&characterEncoding=utf8
      username: root
      password:
      driver-class-name: com.mysql.cj.jdbc.Driver
  batch:
    job: # 제거하면 job.name 이 없는 경우 동작 안함
      names: ${job.name:NONE}
      enabled: false
    jdbc:
      initialize-schema: always
