version: '3.9'

services:
  student_db:
    image: mysql:8.0
    container_name: student_db
    ports:
      - "3306:3306"
    volumes:
      - ./student_mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'cooper2021'
      MYSQL_DATABASE: cooper_db
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
  teacher_db:
    image: mysql:8.0
    container_name: teacher_db
    ports:
      - "3307:3306"
    volumes:
      - ./teacher_mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'cooper2021'
      MYSQL_DATABASE: cooper_db
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
