version: '3.9'

services:
  master_db:
    image: mysql:5.7
    container_name: master_db
    ports:
      - "3306:3306"
    volumes:
      - ./master_db/var/lib/:/var/lib/
      - ./master_db/var/lib/mysql-files/:/var/lib/mysql-files/
#      - ./master_db/etc/:/etc/
    environment:
      MYSQL_ROOT_PASSWORD: 'cooper2021'
      MYSQL_DATABASE: cooper_db
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    networks:
      - net-mysql
  slave_db:
    image: mysql:5.7
    container_name: slave_db
    ports:
      - "3307:3306"
    volumes:
      - ./slave_db/var/lib/mysql-files/:/var/lib/mysql-files/
      - ./slave_db/var/lib/:/var/lib/
#      - ./slave_db/etc/:/etc/
    environment:
      MYSQL_ROOT_PASSWORD: 'cooper2021'
      MYSQL_DATABASE: cooper_db
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    networks:
      - net-mysql


networks:
  net-mysql:
    driver: bridge
