version: "3.8"
services:

  mysql:
    container_name: "batch_practice_db"
    image: mysql:8.0
    ports:
      - '3306:3306'
    volumes:
      - '../../var/lib:/var/lib/mysql'
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=spring_batch
