logging:
  level:
    org.springframework.cloud: trace
    com.example.springfeignclient: debug

request:
  server:
    url: https://apis.data.go.kr/1471000/DURPrdlstInfoService03

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
