spring:
  application:
    name: spring-batch
  datasource:
    url: jdbc:mysql://127.0.0.1:3308/cooper_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: cooper2021
  batch:
    job:
#      enabled: false
      names: ${job.name:NONE}
    jdbc:
      initialize-schema: always
