version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: flyway_practice_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'cooper2021'
      MYSQL_DATABASE: cooper_db
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
