version: "3.9"
services:
  redis:
    container_name: "redis"
    image: "redis"
    ports:
      - "6379:6379"
  mysql:
    container_name: "mysql"
    image: "mysql:8.0"
    ports:
      - "3306:3306"
    volumes:
      - "../../var/lib:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=cooper2021
      - MYSQL_DATABASE=cooper_db
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
