spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cooper_db
    username: root
    password: cooper2021

  flyway:
    enabled: true # flyway ????
    baseline-on-migrate: true # baseline ??
    baseline-version: 1 # baseline-version ?? ?? ??? ? ??.
    url: jdbc:mysql://localhost:3306/cooper_db
    user: root
    password: cooper2021
    locations: classpath:db/migration # ?? script ?? ??

  jpa:
    generate-ddl: false # DDL ?? ??
    open-in-view: false # open-session-in-view = false ?? ??
    hibernate:
      ddl-auto: validate
      use-new-id-generator-mappings: false # hibernate id ?? ??? ??? ??
    show-sql: true # sql ??
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        format_sql: true
        dialects: org.hibernate.dialect.MySQL57Dialect
